name:                arkts-ffi-kt
version:             0.1.0.0
github:              "githubuser/arkts-ffi-kt"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arkts-ffi-kt#readme>

dependencies:
- base >= 4.7 && < 5
- array
- pretty-simple
- prettyprinter
- derive-is-data-con
- derive-topdown
- cmdargs
- syb
- containers
- aeson
- bytestring
- text
- mtl
- transformers
- attoparsec
- parsec
- process


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  arkts-ffi-kt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arkts-ffi-kt

tests:
  arkts-ffi-kt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - arkts-ffi-kt
    - directory
    - aeson
    - bytestring
    - mtl
    - transformers